# Generated by Django 5.2.15 on 2026-06-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_chat_wishlist_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='customer_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
