# Generated by Django 6.0.3 on 2026-03-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, default='', max_length=1000)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('format', models.CharField(blank=True, default='', max_length=255)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('publicationDate', models.CharField(blank=True, default='', max_length=100)),
                ('isbn', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
