# Generated by Django 6.0.3 on 2026-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.CharField(blank=True, default='0.0', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
